INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Andres', 'Gonzales', 'perrocat@gmail.com', '2018-01-04');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Camilin', 'Gopel', 'rocat@gmail.com', '2018-01-15');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Pabla', 'Faraon', 'porselana@gmail.com', '2020-01-04');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Carpitntero', 'Gonzales', 'cat@gmail.com', '2012-03-04');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Gonofleto', 'Gonzales', 'sdsddcat@gmail.com', '2012-03-04');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Camilin', 'Gonzales', 'dcat@gmail.com', '2012-03-04');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Escarbon', 'Gonzales', 's2jajdaat@gmail.com', '2012-03-04');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Carepan', 'Ramirez', 's1ddcat@gmail.com', '2012-03-04');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Colibri', 'Gonz', 'sd2at@gmail.com', '2012-03-04');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Wangler', 'Gonzales', 'sdsskdat@gmail.com', '2012-03-04');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Capaso', 'Gonzales', 'sdsdfdsf33ddcat@gmail.com', '2012-03-04');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Olaf', 'Gonzales', 'sds93t@gmail.com', '2012-03-04');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Cammi', 'Gonzales', 'camiloncat@gmail.com', '2012-03-04');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Julio', 'Gonzales', 'sabort@gmail.com', '2012-03-04');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Marinela', 'Gonzales', 'pickupcat@gmail.com', '2012-03-04');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Escartan', 'Caruseles', 'catcatat@gmail.com', '2012-03-04');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Osabaluo', 'Camrri', 'carepolloat@gmail.com', '2012-03-04');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Juan', 'Pérez', 'juan.perez@email.com', '2020-01-15');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('María', 'García', 'maria.garcia@email.com', '2019-07-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Carlos', 'López', 'carlos.lopez@email.com', '2018-11-02');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Ana', 'Martínez', 'ana.martinez@email.com', '2022-05-10');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Pedro', 'Rodríguez', 'pedro.rodriguez@email.com', '2017-09-30');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Laura', 'Sánchez', 'laura.sanchez@email.com', '2021-03-18');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Javier', 'Gómez', 'javier.gomez@email.com', '2016-08-14');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Sofía', 'Díaz', 'sofia.diaz@email.com', '2015-12-09');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Alejandro', 'Fernández', 'alejandro.fernandez@email.com', '2014-06-27');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Elena', 'Luna', 'elena.luna@email.com', '2013-04-05');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Diego', 'Hernández', 'diego.hernandez@email.com', '2020-06-12');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Valentina', 'Mendoza', 'valentina.mendoza@email.com', '2019-04-25');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Miguel', 'Silva', 'miguel.silva@email.com', '2018-10-08');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Isabella', 'Torres', 'isabella.torres@email.com', '2022-02-17');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Gabriel', 'Pérez', 'gabriel.perez@email.com', '2017-11-29');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Carmen', 'López', 'carmen.lopez@email.com', '2021-08-03');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Francisco', 'Gómez', 'francisco.gomez@email.com', '2016-12-01');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Alejandra', 'Martínez', 'alejandra.martinez@email.com', '2015-05-14');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Daniel', 'Ramírez', 'daniel.ramirez@email.com', '2014-02-22');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Lucía', 'García', 'lucia.garcia@email.com', '2013-09-11');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Andrés', 'Díaz', 'andres.diaz@email.com', '2012-11-20');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Renata', 'Sánchez', 'renata.sanchez@email.com', '2020-03-04');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Santiago', 'Fernández', 'santiago.fernandez@email.com', '2019-07-16');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Valeria', 'Pérez', 'valeria.perez@email.com', '2018-04-29');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Martín', 'Rodríguez', 'martin.rodriguez@email.com', '2017-06-10');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Camila', 'Gómez', 'camila.gomez@email.com', '2016-08-22');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Luis', 'Hernández', 'luis.hernandez@email.com', '2021-02-14');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Victoria', 'Sánchez', 'victoria.sanchez@email.com', '2020-05-07');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Emilio', 'Martínez', 'emilio.martinez@email.com', '2019-09-20');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Paola', 'García', 'paola.garcia@email.com', '2018-11-30');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Joaquín', 'López', 'joaquin.lopez@email.com', '2017-03-03');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Daniela', 'Torres', 'daniela.torres@email.com', '2016-01-15');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Lorenzo', 'Ramírez', 'lorenzo.ramirez@email.com', '2015-08-28');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Renata', 'Silva', 'renata.silva@email.com', '2022-01-06');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Felipe', 'Fernández', 'felipe.fernandez@email.com', '2021-05-12');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Julieta', 'Pérez', 'julieta.perez@email.com', '2020-09-18');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Matías', 'Gómez', 'matias.gomez@email.com', '2019-12-22');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Natalia', 'Martínez', 'natalia.martinez@email.com', '2018-02-25');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Andrés', 'López', 'andres.lopez@email.com', '2017-06-29');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Isabella', 'Torres', 'isabella.torres@email.com', '2016-10-03');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Lucas', 'Ramírez', 'lucas.ramirez@email.com', '2015-04-14');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Catalina', 'García', 'catalina.garcia@email.com', '2014-03-26');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Matías', 'Hernández', 'matias.hernandez@email.com', '2021-07-31');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Antonia', 'Martínez', 'antonia.martinez@email.com', '2020-09-10');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Sebastián', 'López', 'sebastian.lopez@email.com', '2019-02-15');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Luna', 'Gómez', 'luna.gomez@email.com', '2018-11-19');

